### ISSUE TITLE
Exec buildin doesn't exit after exec_command

### ISSUE THREAD

**Issue by monsieurCanard** [Luma-3/Minishell#16]
PROBLEME 
![image](https://github.com/Luma-3/Minishell/assets/136458996/f98e4667-759c-478b-b778-e642b97f1958)

SOLUTION :
![image](https://github.com/Luma-3/Minishell/assets/136458996/8268019b-95a3-4c3e-ba48-9493ee284a00)

AU LIEU DE :
![image](https://github.com/Luma-3/Minishell/assets/136458996/59b03794-06d8-418c-9b27-105ac2b9d04f)

**Comment by Luma-3** [comment]
Issue is handle with new built-ins system !
